baseURL = 'https://cheeseepedia-test-j454z.ondigitalocean.app'
languageCode = 'en-us'
title = '[TESTING] Cheese-E-Pedia'

theme = 'cheeseepedia'

[[module.mounts]]
source = 'cheeseepedia/content'
target = 'content'

[[module.mounts]]
source = 'cheeseepedia/layouts'
target = 'layouts'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true